spring:
  data:
    mongodb:
      database: jap_sen
      host: mongo

  messages:
    encoding: UTF-8
    basename: bundle

config:
  secret: mySuperSecret
  expiration: 21600
  token_prefix: "Bearer "