spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: jap_sen

  messages:
    encoding: UTF-8
    basename: bundle

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
      external-file: "myLogs.log"

config:
  secret: mySuperSecret
  expiration: 21600
  token_prefix: "Bearer "
  warodai_url: "https://warodai.ru/lookup/index.php"