spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: jap_sen

  messages:
    encoding: UTF-8
    basename: bundle

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
    getKanjiRandom:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

config:
  secret: mySuperSecret
  expiration: 21600
  token_prefix: "Bearer "