spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: jap_sen

  messages:
    encoding: UTF-8
    basename: bundle

config:
  secret: mySuperSecret
  expiration: 21600
  token_prefix: "Bearer "